;; ┌────────────────────────────────────────────────────────────────┐

;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▄█░█▀█░█▀▄░█░█░█░░░█▀▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░█░█░█░█░█░█░█░█░░░█▀▀░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/alsa]
type = internal/pulseaudio

;;sink = alsa_output.pci-0000_00_1b.0.analog-stereo
use-ui-max = true
interval = 5
;;<bar-volume>
format-volume = <bar-volume>
format-volume-prefix = " "
format-volume-prefix-foreground = #ebdbb2
format-volume-foreground = #8FC668

format-muted = <label-muted>
format-muted-prefix = "󰖁"
label-muted = " Muted"
label-muted-foreground = #FBC02D

bar-volume-width = 8
bar-volume-gradient = false

bar-volume-indicator = 
bar-volume-indicator-foreground = #8FC668
bar-volume-indicator-font = 2

bar-volume-fill =  ﭳ
bRar-volume-foreground-0 = #8FC668
bar-volume-foreground-1 = #8FC668
bar-volume-foreground-2 = #FBC02D
bar-volume-foreground-3 = #F38BA8
bar-volume-fill-font = 5

bar-volume-empty = ﭳ
#bar-volume-empty-foreground = ${color.fg}
bar-volume-empty-font = 5


click-right = pavucontrol

;  

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
full-at = 98

format-charging = <label-charging>
format-charging-padding = 1
format-charging-prefix = %{T2}%{T-}
format-charging-prefix-background = ${colors.bg}
format-charging-prefix-foreground = ${colors.fg} 
format-charging-underline = ${color.blue}
label-charging = %{T2}%percentage%%%{T-}
label-charging-background = ${colors.bg}  
label-charging-foreground = ${colors.fg} 
label-charging-underline = ${color.blue}
label-charging-padding = 1

format-discharging = <label-discharging>
format-discharging-padding = 1
format-discharging-prefix = %{T2}%{T-}
format-discharging-underline = ${color.blue}
format-discharging-prefix-background = ${colors.bg}
format-discharging-prefix-foreground = ${colors.fg} 
label-discharging = %{T2}%percentage%%%{T-}
label-discharging-background = ${colors.bg}                                                           
label-discharging-foreground = ${colors.fg} 
label-discharging-underline = ${color.blue}
label-discharging-padding = 1

format-full = <label-full>
format-full-padding = 1
format-full-prefix = %{T2}%{T-}
format-full-underline = ${color.blue}
format-full-prefix-background = ${colors.bg}
format-full-prefix-foreground = ${colors.fg}
label-full-underline = ${color.blue}  
label-full = %{T2}%percentage%%%{T-}
label-full-background = ${colors.bg}                                                           
label-full-foreground = ${colors.fg} 
label-full-padding = 1

[module/temperature]
type = internal/temperature

; Seconds to sleep between updates
; Default: 1
interval = 0.5

; Thermal zone to use
; To list all the zone types, run 
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 0

; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; Default reverts to thermal zone setting
;;hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
hwmon-path = /sys/devices/pci0000:00/0000:00:01.3/0000:01:00.0/hwmon/hwmon0/temp1_input

; Threshold temperature to display warning label (in degrees celsius)
; Default: 80
warn-temperature = 65

; Whether or not to show units next to the temperature tokens (°C, °F)
; Default: true
units = true

; Available tags:
;   <label> (default)
;   <ramp>
format = <ramp> <label>

; Available tags:
;   <label-warn> (default)
;   <ramp>
format-warn = <ramp> <label-warn>

; Available tokens:
;   %temperature% (deprecated)
;   %temperature-c%   (default, temperature in °C)
;   %temperature-f%   (temperature in °F)
label = %temperature-c%

; Available tokens:
;   %temperature% (deprecated)
;   %temperature-c%   (default, temperature in °C)
;   %temperature-f%   (temperature in °F)
label-warn = "%temperature-c%"
label-warn-foreground = ${color.secondary}

; Requires the <ramp> tag
; The icon selection will range from 0 to `warn-temperature`
; with the current temperature as index.
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 


[module/date]
type = internal/date

; Seconds to sleep between updates
interval = 1.0

; See "http://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
;;date = %Y-%m-%d%

; Optional time format
;time = " %I:%M %p"
time = "%I:%M"
; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
;;date-alt = %A, %d %B %Y
time-alt = "%d %b %Y"

; Available tags:
;   <label> (default)
format = <label>
format-prefix =""

; Available tokens:
;   %date%
;   %time%
; Default: %date%
label = %time%
label-padding-left = 2
label-foreground = #CFCFCF

[module/menu-ip]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If false, it will be on the right of all the items.
expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Available exec commands:
;   menu-open-LEVEL
;   menu-close
; Other commands will be executed using "/usr/bin/env sh -c $COMMAND"
menu-0-0 = 
menu-0-0-exec = ~/.config/bin/show_ip.sh
menu-0-1 = 
menu-0-1-exec = ~/.config/bin/copyipvpn.sh
menu-0-2 =什
menu-0-2-exec = ~/.config/bin/copyiptarget.sh


menu-1-0 = cancel
menu-1-0-exec = menu-open-0
; Available tags: 
;   <label-toggle> (default) - gets replaced with <label-(open|close)>
;   <menu> (default)
; Note that if you use <label-toggle> you must also include
; the definition for <label-open>

format = <label-toggle> <menu>
format-background = #0D0E0E
format-foreground = #CFCFCF
format-padding = 2


label-open = 
label-close = 

; Optional item separator
; Default: none
label-separator = "   "

[module/cpu]
type = internal/cpu

; Seconds to sleep between updates
; Default: 1
interval = 1

; Available tags:
;   <label> (default)
;   <bar-load>
;   <ramp-load>
;   <ramp-coreload>
;;format = <label> <ramp-coreload>
format = <label>
format-prefix = 

; Available tokens:
;   %percentage% (default) - total cpu load averaged over all cores
;   %percentage-sum% - Cumulative load on all cores
;   %percentage-cores% - load percentage for each core
;   %percentage-core[1-9]% - load percentage for specific core
label = " %percentage%%"

; Spacing between individual per-core ramps
;;ramp-coreload-spacing = 1
;;ramp-coreload-0 = ${cpu.load0}
;;ramp-coreload-1 = ${cpu.load1}

;;ramp-load-0 = ${cpu.load0}
;;ramp-load-1 = ${cpu.load1}

[module/network]
type = internal/network
interface = wlp1s0

; Seconds to sleep between updates
; Default: 1
interval = 1.0

; Test connectivity every Nth update
; A value of 0 disables the feature
; NOTE: Experimental (needs more testing)
; Default: 0
;ping-interval = 3

; @deprecated: Define min width using token specifiers (%downspeed:min% and %upspeed:min%)
; Minimum output width of upload/download rate
; Default: 3
;;udspeed-minwidth = 5

; Accumulate values from all interfaces
; when querying for up/downspeed rate
; Default: false
accumulate-stats = true

; Consider an `UNKNOWN` interface state as up.
; Some devices have an unknown state, even when they're running

; Default: false
unknown-as-up = true

; Available tags:
;   <label-connected> (default)
;   <ramp-signal>
;format-connected = <label-connected>
format-connected = 
format-connected-foreground = #CFCFCF

; Available tags:
;   <label-disconnected> (default)
;format-disconnected = <label-disconnected>
format-disconnected = 
format-disconnected-foreground = #CB3B22

; Available tags:
;   <label-connected> (default)
;   <label-packetloss>
;   <animation-packetloss>
;;format-packetloss = <animation-packetloss> <label-connected>

; Available tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: %ifname% %local_ip%
label-connected = "%{A1:networkmanager_dmenu &:} %essid%%{A}"
label-alt = "a"
; Available tokens:
;   %ifname%    [wireless+wired]
; Default: (none)
label-disconnected = "%{A1:networkmanager_dmenu &:} Offline%{A}"
;;label-disconnected-foreground = #66ffffff

; Available tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: (none)
;label-packetloss = %essid%
;label-packetloss-foreground = #eefafafa

; Only applies if <ramp-signal> is used
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 

; Only applies if <animation-packetloss> is used
;;animation-packetloss-0 = ⚠
;;animation-packetloss-0-foreground = #ffa64c
;;animation-packetloss-1 = ⚠
;;animation-packetloss-1-foreground = #000000
; Framerate in milliseconds
;;animation-packetloss-framerate = 500


[module/workspaces]
type = internal/xworkspaces

; Only show workspaces defined on the same output as the bar
;
; Useful if you want to show monitor specific workspaces
; on different bars
;
; Default: false
pin-workspaces = true

; Create click handler used to focus desktop
; Default: true
enable-click = true

; Create scroll handlers used to cycle desktops
; Default: true
enable-scroll = false

; icon-[0-9]+ = <desktop-name>;<icon>
; NOTE: The desktop name needs to match the name configured by the WM
; You can get a list of the defined desktops using:
; $ xprop -root _NET_DESKTOP_NAMES
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-default = 


; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(active|urgent|occupied|empty)>
; Default: <label-state>
format = <label-state>
format-padding = 0

; Available tokens:
;   %name%
; Default: %name%
label-monitor = %name%

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-active=
label-active-foreground = #d13737

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-occupied= 
label-occupied-foreground = ${color.alternate}

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-urgent = %name%
label-urgent-foreground = ${color.secondary}

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-empty = 
label-empty-foreground = #0D0E0E
;label-empty = 

label-active-padding = 2
label-urgent-padding = 2
label-occupied-padding = 2
label-empty-padding = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/hackthebox]
type = custom/script
interval = 1
exec = ~/.config/bin/hackthebox.sh
click-left = ~/.config/bin/copyipvpn.sh
;click-right = ~/.config/bin/conectvpn.sh
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/target]
type = custom/script
interval = 1
exec = ~/.config/bin/target_to_hack.sh
click-left = ~/.config/bin/copyiptarget.sh
label-padding-right = 3


[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true
occupied-scroll = false


format = <label-state>
format-font = 2

label-focused = ﮊ
label-focused-padding = 1
label-focused-foreground = #8ec07c

label-occupied = ﮊ
label-occupied-padding = 1
label-occupied-foreground = #d79921
label-urgent-foreground = #cc241d
label-urgent = ﮊ
label-urgent-padding = 0

label-empty = ﮊ
label-empty-foreground = #928374
label-empty-padding = 1

[module/rofi-usb-mount]
type = custom/script
exec = ~/.config/polybar/scripts/rofi-usb-mount.sh --check
tail = true
click-left = ~/.config/polybar/scripts/rofi-usb-mount.sh --mount
click-right = ~/.config/polybar/scripts/rofi-usb-mount.sh --umount
click-middle = ~/.config/polybar/scripts/rofi-usb-mount.sh --umount-all
